### ISSUE TITLE
As a user, I would like to create/delete and login/logout of my user account (2)

### ISSUE THREAD

**Issue by PThompson284** [DavidWellsTheDeveloper/cs414-f18-001-Team.name#12]
Acceptance Criteria:
Client:
-Send in user info to register an account
-Send in user credentials to log in to an existing account
-Log out of an account
-Delete an existing account

Server:
-Handle user creation
-Handle user deletion
-Handle login requests
-Handle logout requests

**Comment by tmsdbqk** [comment]
The specs do not mention the need to delete a user account. This will complicate matters if we implement it so I say we avoid doing this.
