### ISSUE TITLE
Client game board

### ISSUE THREAD

**Issue by tmsdbqk** [DavidWellsTheDeveloper/cs414-f18-001-Team.name#23]
As a developer, I need to create a client-side game board interface so that users can change the state of a game object. There should not be any game logic implemented on the client side; rather, there should only be logic handling the visual display and user I/O. This will be done through JavaScript (+ JQuery), with emphasis on AJAX requests.

**Comment by DavidWellsTheDeveloper** [comment]
This was done with different technologies than suggested in the issue, however I think the same result has been achieved.
