### ISSUE TITLE
As a user, I would like to know when no moves are possible (1)

### ISSUE THREAD

**Issue by PThompson284** [DavidWellsTheDeveloper/cs414-f18-001-Team.name#71]
**Acceptance Criteria:**

_Logic:_
* Count the number of available legal moves a player has
* End the game if no moves are available for a player on their turn

**Comment by DavidWellsTheDeveloper** [comment]
@PThompson284, I assigned you since I saw that you were already working on this. It looked like you had already taken care of it with your pull.
